name:  Merge Husky
on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
         key: ${{ secrets.PRIVATE_SSH_KEY }}
         name: id_rsa # optional
         known_hosts: ${{ secrets.HUSKY_HOST_KEY }}
    - name: Fetch, pull and merge from Husky
      run: |
        cd $GITHUB_WORKSPACE
        git remote add husky ssh://${{secrets.HUSKY_REPO_PATH}}
        git checkout -b husky || git checkout husky
        git fetch husky master
        git pull husky master
        git push origin husky
