name:  Merge Husky
on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        ref: 'master'
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
         key: ${{ secrets.PRIVATE_SSH_KEY }}
         known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Fetch, pull and merge from Husky
      run: |
        git config --global user.email ${{secrets.EMAIL}}
        git config --global user.name ${{secrets.USERNAME}}
        git clone ${{secrets.HUSKY_REPO_PATH}} husky_repo
        cd husky_repo
        HUSKY_WORKSPACE=$(pwd)
        git remote add github $GITHUB_WORKSPACE
        git fetch github
        git merge github/master --no-edit
        git push origin master
#
