name:  Merge Husky
on: push
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
         key: ${{ secrets.PRIVATE_SSH_KEY }}
         known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Fetch, pull and merge from Husky
      run: |
        cd $GITHUB_WORKSPACE
        git config --global user.email ${{secrets.EMAIL}}
        git config --global user.name "samcarswell"
        git clone ${{secrets.HUSKY_REPO_PATH}} test2
        ls -la test2
